---
apiVersion: newrelic.fpetkovski.io/v1alpha1
kind: AlertPolicy
metadata:
  name: p3
  labels:
    team: px
spec:
  name: policy3
  incident_preference: "per_policy"
  infraConditions:
    - name: First infra condition
      violationCloseTimer: 60
      eventType: "QueueSample"
      selectValue: "provider.approximateAgeOfOldestMessage.Average"
      comparison: "above"
      alertThreshold:
        timeFunction: any
        value: "5"
        durationMinutes: 5
      integrationProvider: SqsQueue




