apiVersion: alerts.newrelic.io/v1alpha1
kind: SlackNotificationChannel
metadata:
  name: fp-test-123
spec:
  name: "[NewRelic operator] Slack channel test"
  channel: "#dx_playground"
  # spec.url can be left empty if the defaultSlackWebhookUrl is defined
  # when deploying the operator
  url: "abc"
  policySelector:
    team: px
