apiVersion: apiextensions.k8s.io/v1beta1
kind: CustomResourceDefinition
metadata:
  name: emailnotificationchannels.alerts.newrelic.io
spec:
  group: alerts.newrelic.io
  names:
    kind: EmailNotificationChannel
    listKind: EmailNotificationChannelList
    plural: emailnotificationchannels
    singular: emailnotificationchannel
  scope: Namespaced
  subresources:
    status: {}
  validation:
    openAPIV3Schema:
      description: EmailNotificationChannel is the Schema for the EmailNotificationChannels
        API
      properties:
        apiVersion:
          description: 'APIVersion defines the versioned schema of this representation
            of an object. Servers should convert recognized schemas to the latest
            internal value, and may reject unrecognized values. More info: https://git.k8s.io/community/contributors/devel/sig-architecture/api-conventions.md#resources'
          type: string
        kind:
          description: 'Kind is a string value representing the REST resource this
            object represents. Servers may infer this from the endpoint the client
            submits requests to. Cannot be updated. In CamelCase. More info: https://git.k8s.io/community/contributors/devel/sig-architecture/api-conventions.md#types-kinds'
          type: string
        metadata:
          type: object
        spec:
          description: EmailNotificationChannelSpec defines the desired state of EmailNotificationChannel
          properties:
            includeJsonAttachment:
              description: Include JSON attachment with the notification
              type: boolean
            name:
              description: The name of the notification channel created in New Relic
              type: string
            policySelector:
              additionalProperties:
                type: string
              description: A label selector defining the alert policies covered by
                the notification channel
              type: object
            recipients:
              description: A comma-separated value of emails
              type: string
          required:
          - name
          - recipients
          type: object
        status:
          description: NotificationChannelStatus defines the observed state of NotificationChannel
          properties:
            newrelicConfigVersion:
              type: string
            newrelicId:
              description: The resource id in New Relic
              format: int64
              type: integer
            reason:
              description: When a policy fails to be created, the value will be set
                to the error message received from New Relic
              type: string
            status:
              description: The value will be set to `Ready` once the policy has been
                created in New Relic
              type: string
          required:
          - status
          type: object
      type: object
  version: v1alpha1
  versions:
  - name: v1alpha1
    served: true
    storage: true
