apiVersion: apiextensions.k8s.io/v1beta1
kind: CustomResourceDefinition
metadata:
  name: slacknotificationchannels.io.fpetkovski.newrelic
spec:
  group: io.fpetkovski.newrelic
  names:
    kind: SlackNotificationChannel
    listKind: SlackNotificationChannelList
    plural: slacknotificationchannels
    singular: slacknotificationchannel
  scope: Namespaced
  subresources:
    status: {}
  validation:
    openAPIV3Schema:
      description: SlackNotificationChannel is the Schema for the slacknotificationchannels
        API
      properties:
        apiVersion:
          description: 'APIVersion defines the versioned schema of this representation
            of an object. Servers should convert recognized schemas to the latest
            internal value, and may reject unrecognized values. More info: https://git.k8s.io/community/contributors/devel/sig-architecture/api-conventions.md#resources'
          type: string
        kind:
          description: 'Kind is a string value representing the REST resource this
            object represents. Servers may infer this from the endpoint the client
            submits requests to. Cannot be updated. In CamelCase. More info: https://git.k8s.io/community/contributors/devel/sig-architecture/api-conventions.md#types-kinds'
          type: string
        metadata:
          type: object
        spec:
          description: SlackNotificationChannelSpec defines the desired state of SlackNotificationChannel
          properties:
            channel:
              type: string
            url:
              type: string
          required:
          - channel
          - url
          type: object
        status:
          description: SlackNotificationChannelStatus defines the observed state of
            SlackNotificationChannel
          properties:
            newrelicChannelId:
              format: int64
              type: integer
            reason:
              type: string
            status:
              type: string
          required:
          - status
          type: object
      type: object
  version: v1alpha1
  versions:
  - name: v1alpha1
    served: true
    storage: true
