apiVersion: apiextensions.k8s.io/v1beta1
kind: CustomResourceDefinition
metadata:
  name: emailnotificationchannels.newrelic.fpetkovski.io
spec:
  group: newrelic.fpetkovski.io
  names:
    kind: EmailNotificationChannel
    listKind: EmailNotificationChannelList
    plural: emailnotificationchannels
    singular: emailnotificationchannel
  scope: Namespaced
  subresources:
    status: {}
  validation:
    openAPIV3Schema:
      description: EmailNotificationChannel is the Schema for the EmailNotificationChannels
        API
      properties:
        apiVersion:
          description: 'APIVersion defines the versioned schema of this representation
            of an object. Servers should convert recognized schemas to the latest
            internal value, and may reject unrecognized values. More info: https://git.k8s.io/community/contributors/devel/sig-architecture/api-conventions.md#resources'
          type: string
        kind:
          description: 'Kind is a string value representing the REST resource this
            object represents. Servers may infer this from the endpoint the client
            submits requests to. Cannot be updated. In CamelCase. More info: https://git.k8s.io/community/contributors/devel/sig-architecture/api-conventions.md#types-kinds'
          type: string
        metadata:
          type: object
        spec:
          description: EmailNotificationChannelSpec defines the desired state of EmailNotificationChannel
          properties:
            includeJsonAttachment:
              type: boolean
            name:
              type: string
            policySelector:
              additionalProperties:
                type: string
              description: Set is a map of label:value. It implements Labels.
              type: object
            recipients:
              type: string
          required:
          - name
          - recipients
          type: object
        status:
          description: NotificationChannelStatus defines the observed state of NotificationChannel
          properties:
            newrelicChannelId:
              format: int64
              type: integer
            reason:
              type: string
            status:
              type: string
          required:
          - status
          type: object
      type: object
  version: v1alpha1
  versions:
  - name: v1alpha1
    served: true
    storage: true
