apiVersion: apiextensions.k8s.io/v1beta1
kind: CustomResourceDefinition
metadata:
  name: alertpolicies.newrelic.fpetkovski.io
spec:
  group: newrelic.fpetkovski.io
  names:
    kind: AlertPolicy
    listKind: AlertPolicyList
    plural: alertpolicies
    singular: alertpolicy
  scope: Namespaced
  subresources:
    status: {}
  validation:
    openAPIV3Schema:
      description: AlertPolicy is the Schema for the newrelicalertpolicies API
      properties:
        apiVersion:
          description: 'APIVersion defines the versioned schema of this representation
            of an object. Servers should convert recognized schemas to the latest
            internal value, and may reject unrecognized values. More info: https://git.k8s.io/community/contributors/devel/sig-architecture/api-conventions.md#resources'
          type: string
        kind:
          description: 'Kind is a string value representing the REST resource this
            object represents. Servers may infer this from the endpoint the client
            submits requests to. Cannot be updated. In CamelCase. More info: https://git.k8s.io/community/contributors/devel/sig-architecture/api-conventions.md#types-kinds'
          type: string
        metadata:
          type: object
        spec:
          properties:
            apmConditions:
              items:
                properties:
                  alertThreshold:
                    properties:
                      durationMinutes:
                        type: integer
                      operator:
                        enum:
                        - above
                        - below
                        - equal
                        type: string
                      timeFunction:
                        enum:
                        - all
                        - any
                        type: string
                      value:
                        type: string
                    required:
                    - durationMinutes
                    - timeFunction
                    - value
                    type: object
                  conditionScope:
                    enum:
                    - instance
                    - application
                    type: string
                  enabled:
                    type: boolean
                  entities:
                    items:
                      format: int64
                      type: integer
                    type: array
                  metric:
                    type: string
                  name:
                    type: string
                  runbookUrl:
                    type: string
                  type:
                    enum:
                    - apm_app_metric
                    - apm_kt_metric
                    - apm_jvm_metric
                    - browser_metric
                    - mobile_metric
                    type: string
                  userDefined:
                    properties:
                      metric:
                        type: string
                      value_function:
                        enum:
                        - average
                        - min
                        - max
                        - total
                        - sample_size
                        type: string
                    required:
                    - metric
                    - value_function
                    type: object
                  violationCloseTimer:
                    type: integer
                required:
                - alertThreshold
                - entities
                - metric
                - name
                - type
                type: object
              type: array
            incident_preference:
              enum:
              - per_policy
              - per_condition
              - per_condition_and_target
              type: string
            nrqlConditions:
              items:
                properties:
                  alertThreshold:
                    properties:
                      durationMinutes:
                        type: integer
                      operator:
                        enum:
                        - above
                        - below
                        - equal
                        type: string
                      timeFunction:
                        enum:
                        - all
                        - any
                        type: string
                      value:
                        type: string
                    required:
                    - durationMinutes
                    - timeFunction
                    - value
                    type: object
                  enabled:
                    type: boolean
                  name:
                    type: string
                  query:
                    type: string
                  runbookUrl:
                    type: string
                  sinceMinutes:
                    type: integer
                  valueFunction:
                    enum:
                    - single_value
                    - sum
                    type: string
                required:
                - alertThreshold
                - name
                - query
                - sinceMinutes
                - valueFunction
                type: object
              type: array
          required:
          - incident_preference
          type: object
        status:
          properties:
            newrelicPolicyId:
              format: int64
              type: integer
            reason:
              type: string
            status:
              type: string
          required:
          - status
          type: object
      type: object
  version: v1alpha1
  versions:
  - name: v1alpha1
    served: true
    storage: true
