apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: newrelic-alert-manager
rules:
- apiGroups:
    - alerts.newrelic.io
  resources:
    - alertpolicies
    - alertpolicies/status
    - slacknotificationchannels
    - slacknotificationchannels/status
    - emailnotificationchannels
    - emailnotificationchannels/status
  verbs:
    - "*"
- apiGroups:
    - dashboards.newrelic.io
  resources:
    - dashboards
    - dashboards/status
  verbs:
    - "*"
---
kind: ClusterRoleBinding
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: newrelic-alert-manager
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: newrelic-alert-manager
subjects:
  - kind: ServiceAccount
    name: newrelic-alert-manager
    namespace: newrelic-alert-manager
---
apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: newrelic-alert-manager
  namespace: newrelic-alert-manager
rules:
  - apiGroups:
      - ""
    resources:
      - configmaps
      - pods
    verbs:
      - "*"
---
kind: RoleBinding
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: newrelic-alert-manager
  namespace: newrelic-alert-manager
subjects:
  - kind: ServiceAccount
    name: newrelic-alert-manager
    namespace: newrelic-alert-manager
roleRef:
  kind: Role
  name: newrelic-alert-manager
  apiGroup: rbac.authorization.k8s.io