kind: ClusterRoleBinding
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: newrelic-alert-manager
subjects:
- kind: ServiceAccount
  name: newrelic-alert-manager
roleRef:
  kind: Role
  name: newrelic-alert-manager
  apiGroup: rbac.authorization.k8s.io
