apiVersion: apps/v1
kind: Deployment
metadata:
  name: newrelic-alert-manager
spec:
  replicas: 1
  selector:
    matchLabels:
      name: newrelic-alert-manager
  template:
    metadata:
      labels:
        name: newrelic-alert-manager
    spec:
      serviceAccountName: newrelic-alert-manager
      containers:
        - name: newrelic-alert-manager
          # Replace this with the built image name
          image: REPLACE_IMAGE
          command:
          - newrelic-alert-manager
          imagePullPolicy: Always
          env:
            - name: OPERATOR_NAME
              value: "newrelic-alert-manager"
            - name: NEWRELIC_ADMIN_KEY
              value: ""