apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: newrelic-operator
rules:
- apiGroups:
  - newrelic.fpetkovski.io
  resources:
  - alertpolicies
  - slacknotificationchannels
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
